version: '3'
services:
  app:
    image: "ruimo/jobbrokersmoketest:${TAG_NAME:-latest}"
    user: ${UID}:${GID}
    working_dir: /var/home
    volumes:
      - ./client:/var/home
    depends_on:
      - db
      - mq
  worker:
   image: "ruimo/jobbrokersmokeworker:${TAG_NAME:-latest}"
   depends_on:
     - db
     - mq
  db:
    image: "postgres"
  mq:
    image: "rabbitmq"
